spring:
  application:
    name: blogging-platform-api

  config:
    import: optional:file:.env

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:blogging-platform-postgres-db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:mypassword}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect